### PR TITLE
Add custom compile path

### PR DESCRIPTION
**Pull request by assertchris**
Screenshot 2019-07-11 at 12 58 32

With that in your top-level `composer.json`; the compiled files will be placed in `./cache`

### CODE REVIEW

**Comment by assertchris** [comment]
@ircmaxell This feature may interest you...

**Comment by ircmaxell** [comment]
Very interesting... Thanks!

**Comment by bosunski** [comment]
I just made a test. I tested against requiring `.pre` files with `process()` and also when `use`ed as in namespaces. Both worked smoothly. 😎
Here are some of the things I noticed:

- Can the directories created inside `cache` directory be shortened instead of creating the directories or files from the `root` of the FILESYSTEM. I think that might make looking up the processed `.php` files easier.
Screenshot 2019-07-11 at 3 07 51 PM

So instead of `cache/Users/.../project-root/Ace/Ace.php` it can be `cache/Ace/Ace.php`

- If we do `process("test.pre");` the output will be `cachetest.php` at the root of the project. I think a directory separator should be added to the while getting the output path from `pathFor` method so we will have `cache/test.php` (which was expected). However, doing `process(__DIR__ . "/test.pre");` works fine with no issue.

**Comment by assertchris** [comment]
1. It's meant to work like that, because it's possible to put an absolute path in there (shared by multiple projects). The original design of Pre was to colocate the pre and php files, so that the compiled output was effortless to find. This alternative directly competes with that goal, so I'm ok with it being slightly harder to find generated files.

2. I'll change the code so that it adds the separator.

**Comment by bosunski** [comment]
oh! I do understand that well now.

**Comment by bosunski** [comment]
I got this after including in an already existing project.

```
Fatal error: Uncaught Error: Undefined constant 'Composed\BASE_DIR' in /Users/bosunsky/scripts/pre-plugin/source/Composer/Installer.php:42

Stack trace:
#0 /Users/bosunsky/scripts/pre-plugin/source/Composer/Installer.php(27): Pre\Plugin\Composer\Installer->addMacro('/Users/bosunsky...')
#1 phar:///usr/local/bin/composer/src/Composer/Installer/LibraryInstaller.php(79): Pre\Plugin\Composer\Installer->getInstallPath(Object(Composer\Package\CompletePackage))
#2 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(127): Composer\Installer\LibraryInstaller->isInstalled(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
#3 phar:///usr/local/bin/composer/src/Composer/Factory.php(559): Composer\Installer\InstallationManager->isPackageInstalled(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
#4 phar:///usr/local/bin/composer/src/Composer/Factory.php(404): Composer\Factory->purgePackages(Object(Composer\Repo in /Users/bosunsky/scripts/pre-plugin/source/Composer/Installer.php on line 42
```

I'm not sure what could have caused this.

**Comment by bosunski** [comment]
> I got this after including in an already existing project.
> 
> ```
> Fatal error: Uncaught Error: Undefined constant 'Composed\BASE_DIR' in /Users/bosunsky/scripts/pre-plugin/source/Composer/Installer.php:42
> 
> Stack trace:
> #0 /Users/bosunsky/scripts/pre-plugin/source/Composer/Installer.php(27): Pre\Plugin\Composer\Installer->addMacro('/Users/bosunsky...')
> #1 phar:///usr/local/bin/composer/src/Composer/Installer/LibraryInstaller.php(79): Pre\Plugin\Composer\Installer->getInstallPath(Object(Composer\Package\CompletePackage))
> #2 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(127): Composer\Installer\LibraryInstaller->isInstalled(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
> #3 phar:///usr/local/bin/composer/src/Composer/Factory.php(559): Composer\Installer\InstallationManager->isPackageInstalled(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Package\CompletePackage))
> #4 phar:///usr/local/bin/composer/src/Composer/Factory.php(404): Composer\Factory->purgePackages(Object(Composer\Repo in /Users/bosunsky/scripts/pre-plugin/source/Composer/Installer.php on line 42
> ```
> 
> I'm not sure what could have caused this.

I also get this when I run `composer dump-autoload -o`.

**Pull request closed without merging**
